INSERT INTO maatregel (id,omschrijving) VALUES ('51.02.02','Dressen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.11.02','Bemesten plantplaats');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.11.03','Bemesten plantstrook');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.11.12','Bemesten beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.11.13','Bemesten');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.11.15','Bemesten plantenbak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.11.16','Bemesten plantenbak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.12.01','Zaaien');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.12.11','Zaaien ten behoeve van herstel grasmat.');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.13.01','Steken Graszoden');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.13.02','Aanbrengen rolzoden');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.14.03','Watergeven plantenbak/-schaal');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.01','Maken plantplaats');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.02','Maken plantstrook');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.03','Maken plantgat');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.04','Maken plantsleuf');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.11','Laden en transporteren plantmateriaal');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.12','Lossen en zo nodig inkuilen plantmateriaal');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.21','Planten van bomen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.23','Planten van bosplantsoen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.45','Inboeten bosplantsoen (Nazorg)');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.46','Inboeten bosplantsoen (Nazorg)');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.15.48','Inboeten Sierplantsoen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.21.02','Verwerken bestrijdingsmiddel in vak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.21.03','Verwerken bestrijdingsmiddel op boomspiegel');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.01','Maaien bermen en taluds');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.02','Maaien bermstrook langs verharding -extra beurt-');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.05','Verwerken maaisel vrijgekomen op bermen en taluds');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.06','Verwerken maaisel vrijgekomen op bermstrook verh.');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.11','Maaien Gras gedurende .....');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.12','Maaien grasveld');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.13','Maaien grasveld');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.15','Verwerken maaisel vrijgekomen bij maaien grasveld.');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.31','Knippen Graskanten');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.32','Afsteken Graskanten');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.35','Bijmaaien rond bomen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.41','Grasveld ontdoen van blad');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.51','Rollen Grasveld');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.52','Slepen Grasveld');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.53','Beluchten Grasveld');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.54','Diepverluchten grasveld');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.41.55','Verticuteren grasveld');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.01','Onkruid vrij maken');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.02','Onkruidvrij maken vak/plantsoen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.05','Onkruidvrij maken rand beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.06','Onkruidvrij maken plantenbak/-schaal');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.11','Onkruidbeheersing in beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.13','Onkruidbeheersing in rand beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.14','Onkruidbeheersing in plantenbak/-schaal');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.15','Verwerken vrijgekomen materiaal (beplantingsvak)');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.16','Verwerken vrijgekomen materiaal (rand bepl.vak)');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.17','Verwerken vrijgekomen materiaal (haagvoet)');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.18','Verwerken vrijgekomen materiaal (blokhaag)');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.21','Inboeten bosplantsoen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.22','Inboeten Sierplantsoen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.25','Opnemen, scheuren en herplanten van vaste planten');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.31','Verwijderen blad uit beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.51','Uitmaaien beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.52','Uitmaaien rand beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.61','Snoeien sierplantsoen (Zie 51.42.63.)');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.62','Snoeien rand beplantingsvak');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.63','Snoeien struikrozen');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.66','Knippen van bodembedekkende heesters');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.71','Dunnen beplanting');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.72','Vrijstellen beplanting');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.73','Terugzetten beplanting');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.74','Afzetten beplanting');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.42.81','Controleren klim- en leiplanten');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.43.01','Onkruidvrij maken boomspiegel');
INSERT INTO maatregel (id,omschrijving) VALUES ('51.53.02','Onkruidbeheersing in boomspiegel');
